### ISSUE TITLE
qwen2.5 bug

### ISSUE THREAD

**Issue by PinxueGuo** [Deep-Agent/R1-V#56]
Hi, thanks for the great work.
Has qwen2.5 support been verified correctly? I can run qwen2 but get an error when I try qwen2.5:

[rank6]: Traceback (most recent call last):
[rank6]:   File "/gpfs/users/xxx/codes/R1-V/src/open-r1-multimodal/src/open_r1/grpo.py", line 203, in <module>
[rank6]:     main(script_args, training_args, model_args)
[rank6]:   File "/gpfs/users/xxx/codes/R1-V/src/open-r1-multimodal/src/open_r1/grpo.py", line 192, in main
[rank6]:     trainer.train()
[rank6]:   File "/gpfs/users/xxx/miniconda3/envs/r1-v/lib/python3.11/site-packages/transformers/trainer.py", line 2184, in train
[rank6]:     return inner_training_loop(
[rank6]:            ^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/gpfs/users/xxx/miniconda3/envs/r1-v/lib/python3.11/site-packages/transformers/trainer.py", line 2490, in _inner_training_loop
[rank6]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank6]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/gpfs/users/xxx/miniconda3/envs/r1-v/lib/python3.11/site-packages/transformers/trainer.py", line 3598, in training_step
[rank6]:     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
[rank6]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/gpfs/users/xxx/codes/R1-V/src/open-r1-multimodal/src/open_r1/trainer/grpo_trainer.py", line 395, in compute_loss
[rank6]:     completion = unwrapped_model.generate(**prompt_inputs, generation_config=temp_generation_config)
[rank6]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/gpfs/users/xxx/miniconda3/envs/r1-v/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank6]:     return func(*args, **kwargs)
[rank6]:            ^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/gpfs/users/xxx/miniconda3/envs/r1-v/lib/python3.11/site-packages/transformers/generation/utils.py", line 2228, in generate
[rank6]:     result = self._sample(
[rank6]:              ^^^^^^^^^^^^^
[rank6]:   File "/gpfs/users/xxx/miniconda3/envs/r1-v/lib/python3.11/site-packages/transformers/generation/utils.py", line 3257, in _sample
[rank6]:     next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
[rank6]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank6]: RuntimeError: CUDA error: device-side assert triggered
[rank6]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank6]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank6]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions

**Comment by 0xvincii** [comment]
Hi, did you update the latest code and install the env? could you please also upload the running script?

**Comment by PinxueGuo** [comment]
Yes. I consturct the env before the commit version [97d5f95] and update the codes by pulling commit [97d5f95]. 

This is the setup.sh:
```
conda create -n r1-v python=3.11 
conda activate r1-v

# Install the packages in open-r1-multimodal .
cd src/open-r1-multimodal # We edit the grpo.py and grpo_trainer.py in open-r1 repo.
pip install -e ".[dev]"

# Addtional modules
pip install wandb==0.18.3
pip install tensorboardx
pip install qwen_vl_utils torchvision
pip install flash-attn --no-build-isolation

pip install git+https://github.com/huggingface/transformers.git # correct deepspeed support

```

, and this is the running script:
```

cd src/open-r1-multimodal

WANDB_RUN_NAME=Qwen2-VL-2B-GRPO-CLEVR-70k

export DEBUG_MODE="true" # Enable Debug if you want to see the rollout of model during RL
export LOG_PATH="./debug_log_${WANDB_RUN_NAME}.txt"

torchrun --nproc_per_node="8" \
    --nnodes="1" \
    --node_rank="0" \
    --master_addr="127.0.0.1" \
    --master_port="12345" \
    src/open_r1/grpo.py \
    --deepspeed local_scripts/zero3.json \
    --output_dir outputs/${WANDB_RUN_NAME} \
    --model_name_or_path Qwen/Qwen2-VL-2B-Instruct \
    --dataset_name leonardPKU/clevr_cogen_a_train \
    --max_prompt_length 1024 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 2 \
    --logging_steps 1 \
    --bf16 \
    --report_to wandb \
    --gradient_checkpointing false \
    --attn_implementation flash_attention_2 \
    --max_pixels 401408 \
    --num_train_epochs 2 \
    --run_name $WANDB_RUN_NAME \
    --save_steps 100 \
    --save_only_model true \
    --num_generations 8   # number of outputs G in grpo, reduce it would lead to faster training and smaller memory cost but higher variance  

```

**Comment by 0xvincii** [comment]
thank you, we are debuging now, we didn't meet similar problems. please stay tuned

**Comment by 0xvincii** [comment]
Hi, can you try create a new env and rerun the setup.sh? We just tried clone the latest repo, ran the setup.sh to create a new env and ran the script. It goes well.

the script for qwen2.5-vl-3b

```bash
export DEBUG_MODE="true"
export LOG_PATH="./debug_log_clevr_3b_0211.txt"

torchrun --nproc_per_node="4" \
    --nnodes="1" \
    --node_rank="0" \
    --master_addr="127.0.0.1" \
    --master_port="12345" \
    src/open_r1/grpo.py \
    --output_dir ./Qwen2.5-VL-3B-GRPO-clevr-fixpixel_debug \
    --model_name_or_path ./Qwen2.5-VL-3B-Instruct \
    --dataset_name leonardPKU/clevr_cogen_a_train \
    --max_prompt_length 512 \
    --max_completion_length 512 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 2 \
    --logging_steps 1 \
    --bf16 \
    --report_to wandb \
    --deepspeed local_scripts/zero3.json \
    --gradient_checkpointing false \
    --attn_implementation flash_attention_2 \
    --max_pixels 401408 \
    --num_train_epochs 2 \
    --run_name Qwen2-VL-2.5VL-3B-debug \
    --save_steps 100 \
    --save_only_model true \
    --num_generations 4
```

**Comment by PinxueGuo** [comment]
The problem was solved. I found that it was due to a corruption in my Qwen2.5-VL-3B weights file, and by trying to run the Qwen2.5-VL-7B model found that it ran fine.

Thanks for your help, so the current version repo can run Qwen2.5 with no problem at all!

**Comment by JZPeterPan** [comment]
Hi, I got the same error when I tried to train the model with a single gpu. It is fine to train with > 2 GPUs

**Comment by llliuxiao** [comment]
I encounter the same problem when I ran Qwen2-VL-2B on single GPU, but it is good with 4 GPUs.
